
variables:
  restoreBuildProjects: '**/*.csproj'
  buildConfig: Release

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(restoreBuildProjects)'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(restoreBuildProjects)'
      arguments: '-c $(buildConfig)'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '$(restoreBuildProjects)'
      arguments: '-c $(buildConfig) --collect "Code Coverage"'
  
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '-c $(buildConfig) -o $(build.artifactstagingdirectory)'
      zipAfterPublish: True