# Build, Test .NET Core apps
# Demo Pipeline

trigger: 
  - master

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: dotnet build 'src\MyPipelineDemo\MyPipelineDemo.csproj'

  - job: Test
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: dotnet test 'test\MyPipelineDemo.Tests\MyPipelineDemo.Tests.csproj'