# Build, Test .NET Core apps
# Demo Pipeline

trigger: 
  - master

variables:
  buildConfig: 'Debug'

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: dotnet build 'src\MyPipelineDemo.csproj'

  - job: RunTests
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: dotnet test 'test\MyPipelineDemo.Tests\MyPipelineDemo.Tests.csproj'